
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 26 11:48:07 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 23;
  public static final int CONST = 6;
  public static final int CHAR = 10;
  public static final int GREATEROREQUAL = 32;
  public static final int NAMESPACE = 5;
  public static final int LPAREN = 22;
  public static final int GREATER = 30;
  public static final int SEMI = 17;
  public static final int LESS = 31;
  public static final int MINUS = 19;
  public static final int RPAREN = 20;
  public static final int AND = 36;
  public static final int OR = 37;
  public static final int BOOL = 9;
  public static final int COMMA = 16;
  public static final int INC = 26;
  public static final int DIV = 18;
  public static final int LESSOREQUAL = 33;
  public static final int DIFFERENT = 35;
  public static final int PLUS = 14;
  public static final int ASSIGN = 21;
  public static final int EOF = 0;
  public static final int RBRACKET = 25;
  public static final int EQUAL = 34;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int MUL = 15;
  public static final int NUMBER = 8;
  public static final int MOD = 24;
  public static final int IDENT = 7;
  public static final int VOID = 28;
  public static final int LBRACE = 3;
  public static final int READ = 12;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 29;
  public static final int PRINT = 27;
  public static final int DOUBLECOLON = 11;
}

